import type { CreditCardProduct, TravelOffer } from "./types"

export const CREDIT_CARDS: CreditCardProduct[] = [
  { id: "hdfc-regalia", bank: "HDFC", name: "Regalia" },
  { id: "hdfc-millennia", bank: "HDFC", name: "Millennia" },
  { id: "hdfc-dcb", bank: "HDFC", name: "Diners Club Black" },
  { id: "axis-atlas", bank: "Axis", name: "Atlas" },
  { id: "axis-magnus", bank: "Axis", name: "Magnus" },
  { id: "axis-ace", bank: "Axis", name: "Ace" },
  { id: "sbi-cashback", bank: "SBI", name: "Cashback" },
  { id: "sbi-prime", bank: "SBI", name: "Prime" },
  { id: "sbi-elite", bank: "SBI", name: "Elite" },
  { id: "icici-amazon", bank: "ICICI", name: "Amazon Pay" },
  { id: "icici-sapphiro", bank: "ICICI", name: "Sapphiro" },
  { id: "amex-mrcc", bank: "American Express", name: "MRCC" },
  { id: "amex-pt", bank: "American Express", name: "Platinum Travel" },
]

export const DEMO_SELECTED_CARD_IDS = [
  "hdfc-regalia",
  "axis-atlas",
  "sbi-cashback",
  "icici-amazon",
  "amex-mrcc",
]

const nov15 = "2025-11-15"
const nov20 = "2025-11-20"
const oct12 = "2025-10-12"

export const MOCK_OFFERS: TravelOffer[] = [
  {
    id: "mmt-regalia-flights",
    platform: "MakeMyTrip",
    cardId: "hdfc-regalia",
    category: "flights",
    discountType: "instant",
    discountPercentage: 12,
    maximumDiscount: 1200,
    minimumSpend: 5000,
    validUntil: nov15,
    eligible: true,
    confidence: "high",
    restrictions: ["Selected fare types may be excluded"],
    scope: "domestic",
  },
  {
    id: "ct-atlas-flights",
    platform: "Cleartrip",
    cardId: "axis-atlas",
    category: "flights",
    discountType: "instant",
    discountPercentage: 10,
    maximumDiscount: 1500,
    minimumSpend: 10000,
    validUntil: nov20,
    eligible: true,
    confidence: "high",
    restrictions: ["Economy fares only"],
    scope: "domestic",
  },
  {
    id: "emt-sbi-flights",
    platform: "EaseMyTrip",
    cardId: "sbi-cashback",
    category: "flights",
    discountType: "cashback",
    discountPercentage: 8,
    maximumDiscount: 1000,
    minimumSpend: 7500,
    validUntil: nov15,
    eligible: true,
    confidence: "high",
    restrictions: ["Cashback credited within 90 days"],
    scope: "domestic",
  },
  {
    id: "yatra-icici-flights",
    platform: "Yatra",
    cardId: "icici-amazon",
    category: "flights",
    discountType: "instant",
    discountPercentage: 8,
    maximumDiscount: 800,
    minimumSpend: 5000,
    validUntil: nov15,
    eligible: true,
    confidence: "high",
    restrictions: [],
    scope: "domestic",
  },
  {
    id: "mmt-amex-flights",
    platform: "MakeMyTrip",
    cardId: "amex-mrcc",
    category: "flights",
    discountType: "flat",
    flatDiscount: 750,
    maximumDiscount: 750,
    minimumSpend: 8000,
    validUntil: nov15,
    eligible: true,
    confidence: "high",
    restrictions: [],
    scope: "domestic",
  },
  {
    id: "ct-magnus-flights",
    platform: "Cleartrip",
    cardId: "axis-magnus",
    category: "flights",
    discountType: "instant",
    discountPercentage: 7,
    maximumDiscount: 2000,
    minimumSpend: 15000,
    validUntil: nov20,
    eligible: true,
    confidence: "medium",
    restrictions: ["Business class excluded"],
    scope: "international",
  },
  {
    id: "mmt-regalia-intl",
    platform: "MakeMyTrip",
    cardId: "hdfc-regalia",
    category: "flights",
    discountType: "instant",
    discountPercentage: 8,
    maximumDiscount: 2500,
    minimumSpend: 25000,
    validUntil: nov15,
    eligible: true,
    confidence: "high",
    restrictions: ["International routes only"],
    scope: "international",
  },
  {
    id: "mmt-millennia-flights",
    platform: "MakeMyTrip",
    cardId: "hdfc-millennia",
    category: "flights",
    discountType: "instant",
    discountPercentage: 5,
    maximumDiscount: 500,
    minimumSpend: 3000,
    validUntil: nov15,
    eligible: true,
    confidence: "high",
    restrictions: [],
    scope: "domestic",
  },
  {
    id: "atlas-hotels",
    platform: "MakeMyTrip",
    cardId: "axis-atlas",
    category: "hotels",
    discountType: "instant",
    discountPercentage: 15,
    maximumDiscount: 3000,
    minimumSpend: 8000,
    validUntil: nov20,
    eligible: true,
    confidence: "high",
    restrictions: ["Participating hotels"],
    scope: "both",
  },
  {
    id: "regalia-hotels",
    platform: "Cleartrip",
    cardId: "hdfc-regalia",
    category: "hotels",
    discountType: "instant",
    discountPercentage: 10,
    maximumDiscount: 2000,
    minimumSpend: 6000,
    validUntil: nov15,
    eligible: true,
    confidence: "high",
    restrictions: [],
    scope: "domestic",
  },
  {
    id: "sapphiro-hotels",
    platform: "Yatra",
    cardId: "icici-sapphiro",
    category: "hotels",
    discountType: "cashback",
    discountPercentage: 12,
    maximumDiscount: 2500,
    minimumSpend: 10000,
    validUntil: nov20,
    eligible: true,
    confidence: "medium",
    restrictions: ["Cashback within 60 days"],
    scope: "both",
  },
  {
    id: "yatra-amex-hotels",
    platform: "Yatra",
    cardId: "amex-mrcc",
    category: "hotels",
    discountType: "instant",
    discountPercentage: 7,
    maximumDiscount: 1200,
    minimumSpend: 6000,
    validUntil: nov20,
    eligible: true,
    confidence: "high",
    restrictions: [],
    scope: "domestic",
  },
  {
    id: "emt-icici-hotels",
    platform: "EaseMyTrip",
    cardId: "icici-amazon",
    category: "hotels",
    discountType: "instant",
    discountPercentage: 6,
    maximumDiscount: 900,
    minimumSpend: 4500,
    validUntil: nov15,
    eligible: true,
    confidence: "high",
    restrictions: [],
    scope: "domestic",
  },
  {
    id: "emt-prime-hotels",
    platform: "EaseMyTrip",
    cardId: "sbi-prime",
    category: "hotels",
    discountType: "instant",
    discountPercentage: 9,
    maximumDiscount: 1500,
    minimumSpend: 5000,
    validUntil: oct12,
    eligible: true,
    confidence: "low",
    restrictions: ["Verify on platform"],
    scope: "domestic",
    expired: true,
  },
]

export const MOCK_CARD_LAST_FOUR: Record<string, string> = {
  "hdfc-regalia": "4821",
  "axis-atlas": "9034",
  "sbi-cashback": "7712",
  "icici-amazon": "3389",
  "amex-mrcc": "5510",
}

export function getCardById(id: string): CreditCardProduct | undefined {
  return CREDIT_CARDS.find((c) => c.id === id)
}

export function formatCardLabel(card: CreditCardProduct): string {
  return `${card.bank} ${card.name}`
}
