import { clamp } from "./math"
import { buildHorizons, DEMO_AS_OF } from "./time"
import type {
  ConversationSnapshot,
  Destination,
  HistoricalSample,
  HotelSnapshot,
  ObservationBundle,
  SearchSnapshot,
  SocialSnapshot,
  Spot,
  TrafficSegment,
  TrafficSnapshot,
  TripType,
  WeatherSnapshot,
  Portrait,
} from "./types"

const DEMO = "DEMO" as const
const AS_OF = DEMO_AS_OF.slice(0, 10)

interface Seed {
  id: string
  name: string
  region: string
  lat: number
  lng: number
  drive: number
  trips: TripType[]
  portrait: Portrait
  blurb: string
  capacity: string
  season: number
  nightly: number
  typical: number
  occupancyNow: number
  occupancyWeekend: number
  occupancy30: number
  bookingVelocity: number
  bookingBaseline: number
  search: [number, number, number, number]
  searchBaseline: number
  searchTerms: string[]
  intent: [number, number, number]
  intentBaseline: number
  social: [number, number, number] | null
  socialBaseline: number | null
  trafficNow: number
  trafficDay: number
  normalMinutes: number
  incidents: number
  weather: number
  weatherText: string
  rain: number
  snow?: boolean
  history: number[]
  segments?: TrafficSegment[]
}

const MANALI_SEGMENTS: TrafficSegment[] = [
  { id: "murthal", name: "Delhi → Murthal", normalMinutes: 70, trafficMinutes: 78 },
  { id: "chandigarh", name: "Murthal → Chandigarh", normalMinutes: 150, trafficMinutes: 188 },
  { id: "bilaspur", name: "Chandigarh → Bilaspur", normalMinutes: 95, trafficMinutes: 140 },
  { id: "mandi", name: "Bilaspur → Mandi", normalMinutes: 80, trafficMinutes: 102 },
  { id: "kullu", name: "Mandi → Kullu", normalMinutes: 70, trafficMinutes: 96 },
  { id: "manali", name: "Kullu → Manali", normalMinutes: 75, trafficMinutes: 118 },
]

const SEEDS: Seed[] = [
  {
    id: "manali",
    name: "manali",
    region: "kullu, himachal",
    lat: 32.2432,
    lng: 77.1892,
    drive: 9.7,
    trips: ["mountains", "romantic", "roadtrip"],
    portrait: "peaks",
    blurb: "The name everyone already typed.",
    capacity: "A town that fills from the Mall upward. Once the hotels go, the ridge roads follow.",
    season: 0.9,
    nightly: 9500,
    typical: 180,
    occupancyNow: 0.5,
    occupancyWeekend: 0.78,
    occupancy30: 0.74,
    bookingVelocity: 1.9,
    bookingBaseline: 0.046,
    search: [40, 44, 46, 65],
    searchBaseline: 0.18,
    searchTerms: ["manali", "manali hotels", "manali trip", "manali weather", "manali snowfall", "delhi to manali"],
    intent: [86, 98, 130],
    intentBaseline: 0.12,
    social: [40, 48, 58],
    socialBaseline: 0.11,
    trafficNow: 1.05,
    trafficDay: 1.72,
    normalMinutes: 540,
    incidents: 1,
    weather: 0.84,
    weatherText: "clear and cold, good for being outside",
    rain: 0,
    history: [1.1, 2.4, 7.8, 8.3, 8.6, 8.7],
    segments: MANALI_SEGMENTS,
  },
  {
    id: "tirthan",
    name: "tirthan valley",
    region: "banjar, himachal",
    lat: 31.62,
    lng: 77.42,
    drive: 11,
    trips: ["mountains", "nature", "relax", "roadtrip"],
    portrait: "river",
    blurb: "A river valley that has not caught the Manali wave.",
    capacity: "A thin string of homes along the river. It cannot absorb a Manali-sized weekend.",
    season: 0.42,
    nightly: 7200,
    typical: 54,
    occupancyNow: 0.12,
    occupancyWeekend: 0.2,
    occupancy30: 0.32,
    bookingVelocity: 1.05,
    bookingBaseline: 0.028,
    search: [20, 21, 22, 25],
    searchBaseline: 0.11,
    searchTerms: ["tirthan", "tirthan valley", "tirthan hotels"],
    intent: [22, 24, 27],
    intentBaseline: 0.08,
    social: null,
    socialBaseline: null,
    trafficNow: 1.01,
    trafficDay: 1.08,
    normalMinutes: 620,
    incidents: 0,
    weather: 0.93,
    weatherText: "clear, cold water, similar skies to Manali",
    rain: 0,
    history: [0.6, 1.1, 2.6, 2.9, 3.1, 3.3],
  },
  {
    id: "shoja",
    name: "shoja",
    region: "banjar, himachal",
    lat: 31.56,
    lng: 77.35,
    drive: 10.4,
    trips: ["mountains", "nature", "relax"],
    portrait: "meadow",
    blurb: "Meadows above the valley. The search curve is bending up.",
    capacity: "A hamlet. Hype shows up in searches long before the meadows fill.",
    season: 0.48,
    nightly: 5400,
    typical: 36,
    occupancyNow: 0.12,
    occupancyWeekend: 0.24,
    occupancy30: 0.52,
    bookingVelocity: 1.34,
    bookingBaseline: 0.03,
    search: [14, 16, 18, 23],
    searchBaseline: 0.14,
    searchTerms: ["shoja", "shoja himachal", "shoja stay"],
    intent: [12, 14, 18],
    intentBaseline: 0.1,
    social: [6, 9, 14],
    socialBaseline: 0.12,
    trafficNow: 1,
    trafficDay: 1.1,
    normalMinutes: 600,
    incidents: 0,
    weather: 0.88,
    weatherText: "high, clear, cold mornings",
    rain: 0,
    history: [0.6, 1.1, 2.2, 2.6, 2.9, 3.1],
  },
  {
    id: "jibhi",
    name: "jibhi",
    region: "banjar, himachal",
    lat: 31.65,
    lng: 77.34,
    drive: 11.2,
    trips: ["mountains", "nature", "relax"],
    portrait: "cedar",
    blurb: "Wooden houses and a river. Already in the group chats.",
    capacity: "Small. A viral reel fills the homestays in a week.",
    season: 0.58,
    nightly: 6800,
    typical: 48,
    occupancyNow: 0.22,
    occupancyWeekend: 0.36,
    occupancy30: 0.5,
    bookingVelocity: 1.55,
    bookingBaseline: 0.032,
    search: [16, 18, 21, 27],
    searchBaseline: 0.15,
    searchTerms: ["jibhi", "jibhi stay", "jibhi waterfall"],
    intent: [16, 19, 23],
    intentBaseline: 0.1,
    social: [10, 16, 24],
    socialBaseline: 0.14,
    trafficNow: 1.04,
    trafficDay: 1.22,
    normalMinutes: 630,
    incidents: 0,
    weather: 0.86,
    weatherText: "soft sun, cold river",
    rain: 1,
    history: [0.7, 1.5, 3.4, 4.1, 4.6, 5.0],
  },
  {
    id: "shimla",
    name: "shimla",
    region: "shimla, himachal",
    lat: 31.1048,
    lng: 77.1734,
    drive: 7.5,
    trips: ["mountains", "family", "romantic"],
    portrait: "pine",
    blurb: "The ridge everyone from the plains already knows.",
    capacity: "A city that still jams on the Mall.",
    season: 0.8,
    nightly: 8200,
    typical: 220,
    occupancyNow: 0.5,
    occupancyWeekend: 0.7,
    occupancy30: 0.66,
    bookingVelocity: 1.48,
    bookingBaseline: 0.04,
    search: [48, 52, 55, 70],
    searchBaseline: 0.16,
    searchTerms: ["shimla", "shimla hotels", "delhi to shimla"],
    intent: [70, 78, 96],
    intentBaseline: 0.11,
    social: [30, 34, 40],
    socialBaseline: 0.1,
    trafficNow: 1.12,
    trafficDay: 1.58,
    normalMinutes: 420,
    incidents: 2,
    weather: 0.8,
    weatherText: "crisp, good walking weather",
    rain: 0,
    history: [1.4, 2.8, 7.2, 7.6, 7.8, 8.0],
  },
  {
    id: "bir",
    name: "bir",
    region: "kangra, himachal",
    lat: 32.05,
    lng: 76.72,
    drive: 10.5,
    trips: ["adventure", "mountains", "nature"],
    portrait: "ridge",
    blurb: "A paragliding ridge with a long view and a short season of perfect air.",
    capacity: "Cafes along one road. Mornings fill before rooms do.",
    season: 0.7,
    nightly: 6100,
    typical: 70,
    occupancyNow: 0.3,
    occupancyWeekend: 0.4,
    occupancy30: 0.46,
    bookingVelocity: 1.18,
    bookingBaseline: 0.03,
    search: [22, 24, 26, 31],
    searchBaseline: 0.11,
    searchTerms: ["bir billing", "bir paragliding", "bir stay"],
    intent: [20, 22, 26],
    intentBaseline: 0.09,
    social: [12, 14, 17],
    socialBaseline: 0.1,
    trafficNow: 1.03,
    trafficDay: 1.14,
    normalMinutes: 590,
    incidents: 0,
    weather: 0.96,
    weatherText: "clear air, flyable mornings",
    rain: 0,
    history: [0.9, 1.6, 3.8, 4.2, 4.4, 4.6],
  },
  {
    id: "dharamshala",
    name: "dharamshala",
    region: "kangra, himachal",
    lat: 32.219,
    lng: 76.323,
    drive: 9.5,
    trips: ["mountains", "spiritual", "food"],
    portrait: "forest",
    blurb: "McLeod Ganj above the town. Steady, not spiking.",
    capacity: "Split between the town and the upper lanes.",
    season: 0.66,
    nightly: 6400,
    typical: 140,
    occupancyNow: 0.36,
    occupancyWeekend: 0.5,
    occupancy30: 0.52,
    bookingVelocity: 1.16,
    bookingBaseline: 0.033,
    search: [30, 32, 34, 39],
    searchBaseline: 0.1,
    searchTerms: ["dharamshala", "mcleod ganj", "dharamshala trip"],
    intent: [28, 30, 34],
    intentBaseline: 0.08,
    social: [16, 18, 20],
    socialBaseline: 0.08,
    trafficNow: 1.06,
    trafficDay: 1.24,
    normalMinutes: 560,
    incidents: 0,
    weather: 0.82,
    weatherText: "mild, a little cloud on the ridge",
    rain: 2,
    history: [1.2, 2.2, 5.1, 5.4, 5.6, 5.5],
  },
  {
    id: "mussoorie",
    name: "mussoorie",
    region: "dehradun, uttarakhand",
    lat: 30.4598,
    lng: 78.066,
    drive: 6.2,
    trips: ["mountains", "family", "romantic"],
    portrait: "pine",
    blurb: "Close enough for a Delhi whim. The whim already happened.",
    capacity: "A mall road that saturates by Saturday noon.",
    season: 0.74,
    nightly: 8800,
    typical: 160,
    occupancyNow: 0.42,
    occupancyWeekend: 0.74,
    occupancy30: 0.6,
    bookingVelocity: 1.72,
    bookingBaseline: 0.042,
    search: [36, 40, 44, 62],
    searchBaseline: 0.15,
    searchTerms: ["mussoorie", "mussoorie hotels", "delhi to mussoorie"],
    intent: [40, 48, 66],
    intentBaseline: 0.12,
    social: [18, 22, 29],
    socialBaseline: 0.1,
    trafficNow: 1.08,
    trafficDay: 1.66,
    normalMinutes: 360,
    incidents: 1,
    weather: 0.78,
    weatherText: "pleasant, hazy afternoons",
    rain: 0,
    history: [1.3, 2.6, 7.0, 7.4, 7.6, 7.7],
  },
  {
    id: "rishikesh",
    name: "rishikesh",
    region: "dehradun, uttarakhand",
    lat: 30.0869,
    lng: 78.2676,
    drive: 5.5,
    trips: ["spiritual", "adventure", "nightlife"],
    portrait: "ghats",
    blurb: "The river is the plan. So is everyone else's.",
    capacity: "Ghats and cafes bunch up even when rooms remain.",
    season: 0.7,
    nightly: 5200,
    typical: 200,
    occupancyNow: 0.4,
    occupancyWeekend: 0.58,
    occupancy30: 0.5,
    bookingVelocity: 1.36,
    bookingBaseline: 0.035,
    search: [42, 46, 49, 64],
    searchBaseline: 0.14,
    searchTerms: ["rishikesh", "rishikesh rafting", "delhi to rishikesh"],
    intent: [48, 54, 70],
    intentBaseline: 0.11,
    social: [22, 26, 33],
    socialBaseline: 0.1,
    trafficNow: 1.1,
    trafficDay: 1.48,
    normalMinutes: 320,
    incidents: 0,
    weather: 0.8,
    weatherText: "warm days, good for the river",
    rain: 0,
    history: [1.5, 2.9, 6.2, 6.5, 6.8, 6.6],
  },
  {
    id: "nainital",
    name: "nainital",
    region: "kumaon, uttarakhand",
    lat: 29.391,
    lng: 79.454,
    drive: 7.2,
    trips: ["family", "mountains", "romantic"],
    portrait: "lake",
    blurb: "The lake is the bottleneck.",
    capacity: "The flats around the lake fill before the hills do.",
    season: 0.76,
    nightly: 7900,
    typical: 150,
    occupancyNow: 0.44,
    occupancyWeekend: 0.69,
    occupancy30: 0.58,
    bookingVelocity: 1.5,
    bookingBaseline: 0.038,
    search: [34, 38, 41, 55],
    searchBaseline: 0.13,
    searchTerms: ["nainital", "nainital hotels", "nainital weekend"],
    intent: [36, 40, 52],
    intentBaseline: 0.1,
    social: [14, 16, 20],
    socialBaseline: 0.09,
    trafficNow: 1.07,
    trafficDay: 1.5,
    normalMinutes: 430,
    incidents: 0,
    weather: 0.76,
    weatherText: "clear lake light, cool evenings",
    rain: 0,
    history: [1.2, 2.5, 6.8, 7.2, 7.4, 7.5],
  },
  {
    id: "chakrata",
    name: "chakrata",
    region: "dehradun, uttarakhand",
    lat: 30.703,
    lng: 77.87,
    drive: 7,
    trips: ["mountains", "nature", "relax"],
    portrait: "forest",
    blurb: "A cantonment hill with rooms still on the board.",
    capacity: "Limited stays, but they are not being taken.",
    season: 0.5,
    nightly: 4800,
    typical: 42,
    occupancyNow: 0.16,
    occupancyWeekend: 0.2,
    occupancy30: 0.28,
    bookingVelocity: 0.72,
    bookingBaseline: 0.03,
    search: [10, 11, 11, 12],
    searchBaseline: 0.08,
    searchTerms: ["chakrata", "chakrata stay", "chakrata trip"],
    intent: [9, 9, 10],
    intentBaseline: 0.06,
    social: null,
    socialBaseline: null,
    trafficNow: 1.01,
    trafficDay: 1.08,
    normalMinutes: 400,
    incidents: 0,
    weather: 0.74,
    weatherText: "quiet forest weather",
    rain: 0,
    history: [0.5, 1.0, 2.4, 2.6, 2.8, 2.7],
  },
  {
    id: "dehradun",
    name: "dehradun",
    region: "dehradun, uttarakhand",
    lat: 30.3165,
    lng: 78.0322,
    drive: 5.2,
    trips: ["food", "family", "roadtrip"],
    portrait: "valley",
    blurb: "Not a viewpoint. A city about to host everybody's weekend.",
    capacity: "Hotels along Rajpur Road absorb a lot, then stop.",
    season: 0.6,
    nightly: 5600,
    typical: 260,
    occupancyNow: 0.38,
    occupancyWeekend: 0.58,
    occupancy30: 0.48,
    bookingVelocity: 1.8,
    bookingBaseline: 0.034,
    search: [28, 33, 36, 51],
    searchBaseline: 0.12,
    searchTerms: ["dehradun trip", "dehradun hotels", "places near dehradun", "dehradun weekend", "dehradun weather"],
    intent: [30, 34, 44],
    intentBaseline: 0.1,
    social: [12, 14, 16],
    socialBaseline: 0.08,
    trafficNow: 1.06,
    trafficDay: 1.42,
    normalMinutes: 300,
    incidents: 1,
    weather: 0.83,
    weatherText: "clear, warm afternoons",
    rain: 0,
    history: [1.6, 3.0, 6.4, 6.8, 7.1, 7.0],
  },
  {
    id: "jaipur",
    name: "jaipur",
    region: "rajasthan",
    lat: 26.9124,
    lng: 75.7873,
    drive: 5.5,
    trips: ["food", "romantic", "family", "roadtrip"],
    portrait: "fort",
    blurb: "Pink city, ordinary October heat, steady interest.",
    capacity: "A large city. Tourist lanes crowd before hotels do.",
    season: 0.55,
    nightly: 5900,
    typical: 400,
    occupancyNow: 0.34,
    occupancyWeekend: 0.46,
    occupancy30: 0.62,
    bookingVelocity: 1.22,
    bookingBaseline: 0.025,
    search: [50, 52, 54, 60],
    searchBaseline: 0.08,
    searchTerms: ["jaipur", "jaipur weekend", "jaipur hotels"],
    intent: [40, 42, 48],
    intentBaseline: 0.07,
    social: [20, 22, 25],
    socialBaseline: 0.07,
    trafficNow: 1.15,
    trafficDay: 1.3,
    normalMinutes: 320,
    incidents: 0,
    weather: 0.7,
    weatherText: "warm, dry, fine after dusk",
    rain: 0,
    history: [2.0, 3.2, 5.4, 5.6, 5.8, 5.7],
  },
  {
    id: "udaipur",
    name: "udaipur",
    region: "rajasthan",
    lat: 24.5854,
    lng: 73.7125,
    drive: 12.5,
    trips: ["romantic", "food", "relax"],
    portrait: "palace",
    blurb: "Lakes and a long drive. Hype is old, not new.",
    capacity: "The old city is the pinch point, not the hotel stock.",
    season: 0.58,
    nightly: 7400,
    typical: 180,
    occupancyNow: 0.36,
    occupancyWeekend: 0.5,
    occupancy30: 0.7,
    bookingVelocity: 1.2,
    bookingBaseline: 0.026,
    search: [33, 35, 36, 40],
    searchBaseline: 0.07,
    searchTerms: ["udaipur", "udaipur lakes", "udaipur hotels"],
    intent: [24, 25, 28],
    intentBaseline: 0.06,
    social: [14, 15, 17],
    socialBaseline: 0.06,
    trafficNow: 1.04,
    trafficDay: 1.18,
    normalMinutes: 720,
    incidents: 0,
    weather: 0.74,
    weatherText: "warm days, kind evenings",
    rain: 0,
    history: [1.8, 2.8, 5.0, 5.3, 5.5, 5.6],
  },
  {
    id: "agra",
    name: "agra",
    region: "uttar pradesh",
    lat: 27.175,
    lng: 78.008,
    drive: 3.8,
    trips: ["family", "romantic", "roadtrip"],
    portrait: "monument",
    blurb: "A monument with a queue, not a weekend to linger in.",
    capacity: "The monument is the crowd. The city is not the point.",
    season: 0.5,
    nightly: 4200,
    typical: 220,
    occupancyNow: 0.3,
    occupancyWeekend: 0.42,
    occupancy30: 0.55,
    bookingVelocity: 1.08,
    bookingBaseline: 0.02,
    search: [55, 56, 57, 60],
    searchBaseline: 0.05,
    searchTerms: ["agra", "taj mahal", "delhi to agra"],
    intent: [26, 27, 29],
    intentBaseline: 0.04,
    social: [18, 18, 19],
    socialBaseline: 0.04,
    trafficNow: 1.18,
    trafficDay: 1.36,
    normalMinutes: 230,
    incidents: 0,
    weather: 0.58,
    weatherText: "hot by noon, harsh light",
    rain: 0,
    history: [2.2, 3.4, 6.0, 6.2, 6.4, 6.3],
  },
]

function occupancyFor(seed: Seed, leadDays: number, weekend: boolean): number {
  const towardWeekend = clamp(leadDays / 5, 0, 1)
  const base = seed.occupancyNow + (seed.occupancyWeekend - seed.occupancyNow) * towardWeekend
  const towardMonth = clamp((leadDays - 5) / 25, 0, 1)
  const future = base + (seed.occupancy30 - seed.occupancyWeekend) * towardMonth
  const bump = weekend && leadDays >= 4 && leadDays <= 12 && seed.occupancyWeekend >= 0.55 ? 0.05 : 0
  return clamp(future + bump, 0.05, 0.93)
}

function hotelSeries(seed: Seed, stayStart: string, stayEnd: string, occupancy: number): HotelSnapshot[] {
  const available = Math.max(1, Math.round(seed.typical * (1 - occupancy)))
  const daily = seed.bookingVelocity * seed.bookingBaseline
  const span = 7
  const opening = Math.min(seed.typical, Math.round(available / Math.max(0.18, 1 - daily * span)))
  const dates = ["2026-09-28", "2026-10-01", "2026-10-03", AS_OF]
  return dates.map((observedAt, index) => {
    const progressed = opening + (available - opening) * (index / (dates.length - 1))
    return {
      destinationId: seed.id,
      observedAt: `${observedAt}T08:00:00+05:30`,
      stayStart,
      stayEnd,
      availableProperties: Math.round(progressed),
      typicalAvailable: seed.typical,
      medianNightlyInr: seed.nightly,
      source: "fixture accommodation ledger",
      type: DEMO,
    }
  })
}

function buildHotels(): HotelSnapshot[] {
  const horizons = buildHorizons(DEMO_AS_OF)
  const rows: HotelSnapshot[] = []
  for (const seed of SEEDS) {
    for (const horizon of horizons) {
      rows.push(...hotelSeries(seed, horizon.start, horizon.end, occupancyFor(seed, horizon.leadDays, horizon.weekend)))
    }
  }
  return rows
}

function buildSearch(): SearchSnapshot[] {
  const dates = ["2026-09-05", "2026-09-21", "2026-09-28", AS_OF]
  return SEEDS.flatMap((seed) => dates.map((date, index) => ({
    destinationId: seed.id,
    observedAt: `${date}T07:30:00+05:30`,
    index: seed.search[index] ?? seed.search[seed.search.length - 1]!,
    terms: seed.searchTerms,
    source: "fixture search-trend ledger",
    type: DEMO,
  })))
}

function buildConversations(): ConversationSnapshot[] {
  const dates = ["2026-09-21", "2026-09-28", AS_OF]
  return SEEDS.flatMap((seed) => dates.map((date, index) => {
    const planning = seed.intent[index] ?? seed.intent[seed.intent.length - 1]!
    return {
      destinationId: seed.id,
      observedAt: `${date}T07:20:00+05:30`,
      windowDays: 7,
      counts: {
        PLANNING_TRIP: planning,
        BOOKING: Math.round(planning * 0.35),
        RESEARCHING: Math.round(planning * 0.4),
        ASKING_CROWD: Math.round(planning * 0.12),
        RECOMMENDING: Math.round(planning * 0.08),
      },
      samples: index === 2 ? [`Planning ${seed.name} this weekend.`] : [],
      source: "fixture travel-discussion ledger",
      type: DEMO,
    }
  }))
}

function buildSocial(): SocialSnapshot[] {
  const dates = ["2026-09-21", "2026-09-28", AS_OF]
  return SEEDS.flatMap((seed) => {
    if (!seed.social) return []
    return dates.map((date, index) => ({
      destinationId: seed.id,
      observedAt: `${date}T07:10:00+05:30`,
      mentions: seed.social![index]!,
      engagement: seed.social![index]! * 18,
      creators: Math.max(1, Math.round(seed.social![index]! / 4)),
      source: "fixture public-post ledger",
      type: DEMO,
    }))
  })
}

function buildTraffic(): TrafficSnapshot[] {
  return SEEDS.map((seed) => ({
    destinationId: seed.id,
    observedAt: `${AS_OF}T08:40:00+05:30`,
    normalMinutes: seed.normalMinutes,
    trafficMinutes: Math.round(seed.normalMinutes * seed.trafficNow),
    incidents: seed.incidents,
    segments: seed.segments ?? [{
      id: "approach",
      name: `Delhi → ${seed.name}`,
      normalMinutes: seed.normalMinutes,
      trafficMinutes: Math.round(seed.normalMinutes * seed.trafficDay),
    }],
    predictedTravelDayRatio: seed.trafficDay,
    source: "fixture route ledger",
    type: DEMO,
  }))
}

function buildWeather(): WeatherSnapshot[] {
  const horizons = buildHorizons(DEMO_AS_OF)
  return SEEDS.flatMap((seed) => horizons.map((horizon) => ({
    destinationId: seed.id,
    observedAt: `${AS_OF}T08:18:00+05:30`,
    validOn: horizon.start,
    summary: seed.weatherText,
    score: clamp(seed.weather - horizon.leadDays * 0.002, 0.3, 0.98),
    rainMm: seed.rain,
    snow: Boolean(seed.snow),
    roadClosure: false,
    tempC: seed.portrait === "peaks" || seed.portrait === "meadow" ? 12 : 24,
    source: "fixture weather ledger",
    type: DEMO,
  })))
}

function buildHistory(): HistoricalSample[] {
  const years = [2020, 2021, 2022, 2023, 2024, 2025]
  return SEEDS.flatMap((seed) => years.map((year, index) => ({
    destinationId: seed.id,
    year,
    month: 10,
    crowdIndex: seed.history[index] ?? 4,
    anomalous: year === 2020 || year === 2021,
    note: year === 2020 || year === 2021 ? "COVID period. Not a normal season." : undefined,
  })))
}

const SPOTS: Spot[] = [
  { id: "jogini", destinationId: "manali", name: "Jogini falls", kind: "waterfall", sensitivity: "moderate", safety: 0.7, access: "a short hike from Vashisht" },
  { id: "gulaba", destinationId: "manali", name: "Gulaba", kind: "meadow", sensitivity: "high", safety: 0.55, access: "past the tunnel, fragile in snow" },
  { id: "tirthan-bank", destinationId: "tirthan", name: "the river steps at Banjar", kind: "river", sensitivity: "low", safety: 0.8, access: "beside the road" },
  { id: "jana", destinationId: "jibhi", name: "Jana waterfall", kind: "waterfall", sensitivity: "moderate", safety: 0.66, access: "a walk through the village" },
  { id: "shoja-meadow", destinationId: "shoja", name: "the upper meadow", kind: "meadow", sensitivity: "moderate", safety: 0.74, access: "above the homestays" },
  { id: "serolsar", destinationId: "shoja", name: "Serolsar lake", kind: "lake", sensitivity: "high", safety: 0.6, access: "a longer trail, leave it quiet" },
]

export function loadFixtureBundle(): ObservationBundle {
  const destinations: Destination[] = SEEDS.map((seed) => ({
    id: seed.id,
    name: seed.name,
    region: seed.region,
    lat: seed.lat,
    lng: seed.lng,
    driveHoursFromDelhi: seed.drive,
    tripTypes: seed.trips,
    portrait: seed.portrait,
    blurb: seed.blurb,
    capacityNote: seed.capacity,
    seasonIntensity: seed.season,
    searchBaselineWeekly: seed.searchBaseline,
    intentBaselineWeekly: seed.intentBaseline,
    socialBaselineWeekly: seed.socialBaseline,
    bookingBaselineDaily: seed.bookingBaseline,
  }))
  return {
    destinations,
    hotels: buildHotels(),
    search: buildSearch(),
    conversations: buildConversations(),
    social: buildSocial(),
    traffic: buildTraffic(),
    weather: buildWeather(),
    history: buildHistory(),
    spots: SPOTS,
  }
}

export const FIXTURE_PROVIDERS = [
  { id: "hotels", mode: "fixture" as const, source: "fixture accommodation ledger", note: "Availability contraction. Not confirmed bookings. Not a live channel." },
  { id: "search", mode: "fixture" as const, source: "fixture search-trend ledger", note: "Seasonal search index. Not a live Google query." },
  { id: "conversation", mode: "fixture" as const, source: "fixture travel-discussion ledger", note: "Intent-weighted lines, not generic mentions." },
  { id: "social", mode: "fixture" as const, source: "fixture public-post ledger", note: "Optional. Instagram is not connected." },
  { id: "traffic", mode: "fixture" as const, source: "fixture route ledger", note: "Segment durations. Today's roads are not the weekend's roads." },
  { id: "weather", mode: "fixture" as const, source: "fixture weather ledger", note: "A forecast snapshot, labelled demo." },
  { id: "places", mode: "fixture" as const, source: "editorial places", note: "A short verified list. Fragile spots stay off the map." },
]
